### ISSUE TITLE
Multiple warnings in spectrum widget realization

### ISSUE THREAD

**Issue by BatchDrake** [BatchDrake/suscan#14]
This has been observed for a while now, in the standard error output:

```
(suscan:23349): Gdk-CRITICAL **: 23:05:35.096: gdk_window_create_similar_surface: assertion 'GDK_IS_WINDOW (window)' failed

(suscan:23349): Gtk-CRITICAL **: 23:05:42.405: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed
```

This could imply that we are failing to create the best surface for the spectrum widget. Although it is not prioritary, it is polluting the error output, potentially masking other problems.

**Comment by chris4git** [comment]
Hi, I add :

(suscan:13457): Gtk-CRITICAL **: 21:28:58.126: gtk_combo_box_set_active: assertion 'GTK_IS_COMBO_BOX (combo_box)' failed
