### ISSUE TITLE
Can't test suscan library

### ISSUE THREAD

**Issue by andruxa-smirnov** [BatchDrake/suscan#16]
I build dependencies (suscan) and install it. When i run "suscan", to test installation, i received next message: "suscan: error while loading shared libraries: libsigutils.so.0: cannot open shared object file: No such file or directory". Previously i build sigutils and install it too.
Ubuntu 18.04, x64.

**Comment by BatchDrake** [comment]
This seems a PATH problem. Can you try the following:

```
% export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
% suscan
```

**Comment by miek** [comment]
You may just need to run `sudo ldconfig` to update the linker cache.

**Comment by andruxa-smirnov** [comment]
> This seems a PATH problem. Can you try the following:
> 
> ```
> % export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
> % suscan
> ```

Yes. That is proper solution. Thanks!
