### ISSUE TITLE
SoapySDR headers not found on macOS

### ISSUE THREAD

**Issue by mehdideveloper** [BatchDrake/suscan#34]
Hey
As you know I test on 2 MacBooks.
On one MacBook, I have compiled SoapySDR from source, so there's no issues.
On the other one, I have installed it via brew. On this second machine, I get error:
`/Users/mehdi/Documents/source/suscan/analyzer/source.h:30:10: fatal error: 'SoapySDR/Device.h' file not found`
Well I fixed it temporarily by setting the CPATH variable in command line.
Couldn't find any strange things in your CMakeLists

**Comment by BatchDrake** [comment]
I could not reproduce this one. What version of SoapySDR are you using?

**Comment by mehdideveloper** [comment]
On the one that has issues:

```
Lib Version: v0.7.2-release
API Version: v0.7.1
ABI Version: v0.7
Install root: /usr/local
Search path:  /usr/local/lib/SoapySDR/modules0.7
```

**Comment by BatchDrake** [comment]
Strange. pkg-config should provide the right paths for this. What does `pkg-config SoapySDR --cflags --libs` print?

**Comment by mehdideveloper** [comment]
```
-L/usr/local/Cellar/soapysdr/0.7.2/lib -lSoapySDR
```
So the libraries are ok, but for some reason the headers were not found !

**Comment by BatchDrake** [comment]
Changed a bunch of things in develop, any news regarding this issue?

**Comment by mehdideveloper** [comment]
Hmmm. I am not sure if it was because of the change or some changes in my system, but a clean build from scratch works without problems now 👍

**Comment by BatchDrake** [comment]
There was an issue with headers in general, after building in Mac I may
have fixed a bunch of issues at a time.
