### ISSUE TITLE
Wrong linker library in file

### ISSUE THREAD

**Issue by mehdideveloper** [BatchDrake/suscan#35]
Hey
This is a weird issue:
While compiling, I got this:
`ld: library not found for -l-L/usr/local/opt/qt/lib`
It turned out to be inside `build/CMakeFiles/suscan.dir/link.txt`
There was an empty `-l` . I removed it and compile succeeded

**Comment by BatchDrake** [comment]
Reproduced and already looking into it.

**Comment by BatchDrake** [comment]
It fixed itself by simply removing all contents from the `build` directory and running `cmake ..` on it again. Are you compiling from a clean build directory?

**Comment by mehdideveloper** [comment]
I will double check
