### ISSUE TITLE
cc: warning: argument unused during compilation: '-s' [-Wunused-command-line-argument]

### ISSUE THREAD

**Issue by jeffpc** [BatchDrake/suscan#46]
When making a release build, clang outputs the following for each .c file:

```
cc: warning: argument unused during compilation: '-s' [-Wunused-command-line-argument]
```

I'm assuming this is supposed to be the strip option on gcc, which is AFAIK a linker option.  Therefore, it should *not* be set on `CMAKE_C_FLAGS_RELEASE` but rather on whatever the linking equivalent is.

**Comment by jeffpc** [comment]
I should add, the build succeeds just fine.  It's just noisy, that's all.

**Comment by BatchDrake** [comment]
Done. Changes in develop now.

**Comment by jeffpc** [comment]
Fix works.  It looks so much better now :)
