### ISSUE TITLE
suscan doesn't actually use volk?

### ISSUE THREAD

**Issue by FFY00** [BatchDrake/suscan#50]
Hi, when packing this for arch I noticed the following warning. Looks like suscan isn't actually using volk, if that's the case, the dependency can be removed. Could you investigate? Thanks :grin:.

```
suscan W: Unused shared library '/usr/lib/libvolk.so.2.3' by file ('usr/lib/libsuscan.so')
```

**Comment by BatchDrake** [comment]
You are right, Volk is used in suscan _through_ sigutils, and the only direct use of Volk comes from certain macros in ```ncqo.h```. I'll remove this dependency ASAP.

**Comment by BatchDrake** [comment]
This ended up being a sigutils issue, related to the corresponding .pc file referring to unnecesary libs (volk and fftw3f). Changes are in develop and scheduled for the next release. SigDigger has been changed too in order to rely on fftw3f explicitly.

**Comment by BatchDrake** [comment]
I forgot to mention that the changes are in the `develop` branch of all projects.

**Comment by FFY00** [comment]
Hum, okay. I'll wait for a release, thanks!

**Comment by BatchDrake** [comment]
FYI I am already working on 0.2.0. I'm marking this as fixed as changes are already in develop.

**Comment by FFY00** [comment]
Thanks :blush:
