### ISSUE TITLE
Suscli radio profile setting not changing regardless of index or name used. 

### ISSUE THREAD

**Issue by alphafox02** [BatchDrake/suscan#54]
Before I forget. With the latest Suscli dev branch, I'm unable to change the radio profile using the following commands

Suscli radio profile 2 (replace 2 with any profile index or name)

Initially I was stuck with whatever UI Profile was (index number 1). I then deleted the Suscan sources file. Used Suscli makeprof to create new profiles which resulted in the Default, Airspy, and an IP/port profile.

Now when I start Suscli radio, no matter which profile I pick, it's the index number one Default device (is the Airspy just like the number 2 index) so at least I can use it. However, I think something is preventing the user from changing profiles.

**Comment by alphafox02** [comment]
After deleting the profiles and trying again, it does seem to be working as intended. I'll keep testing and close this issue if that's the case.

**Comment by BatchDrake** [comment]
Hi,

You are missing the = between `profile` and `2`

```
$ suscli radio profile=2
```

**Comment by alphafox02** [comment]
My mistake, that was it. Profiles are selectable.
